### ISSUE TITLE
management tab in UI fails to serve content

### ISSUE THREAD

**Issue by qgeissmann** [gilestrolab/pySolo-Video#67]
Nothing get displayed on the page http://192.169.123.1/more.
Chrome console:
```
Uncaught SyntaxError: Unexpected token =
jquery.min.js:2 Resource interpreted as Font but transferred with MIME type text/html: "http://192.169.123.1/static/fonts/fontawesome-webfont.woff2?v=4.3.0".jquery.min.js:2 (anonymous function)jquery.min.js:2 m.Callbacks.jjquery.min.js:2 m.Callbacks.k.fireWithjquery.min.js:2 m.extend.readyjquery.min.js:2 J
angular.min.js:103 Error: [ng:areq] http://errors.angularjs.org/1.3.11/ng/areq?p0=moreController&p1=not%20aNaNunction%2C%20got%20undefined
    at Error (native)
    at http://192.169.123.1/static/js/vendor/angular.min.js:6:417
    at Qb (http://192.169.123.1/static/js/vendor/angular.min.js:19:417)
    at sb (http://192.169.123.1/static/js/vendor/angular.min.js:20:1)
    at $get (http://192.169.123.1/static/js/vendor/angular.min.js:76:140)
    at link (http://192.169.123.1/static/js/vendor/angular-route.min.js:7:268)
    at $ (http://192.169.123.1/static/js/vendor/angular.min.js:70:488)
    at v (http://192.169.123.1/static/js/vendor/angular.min.js:59:443)
    at g (http://192.169.123.1/static/js/vendor/angular.min.js:52:9)
    at http://192.169.123.1/static/js/vendor/angular.min.js:51:118angular.min.js:103 (anonymous function)angular.min.js:77 $getangular.min.js:70 $angular.min.js:59 vangular.min.js:52 gangular.min.js:51 (anonymous function)angular.min.js:52 $get.hangular.min.js:56 langular-route.min.js:6 xangular.min.js:129 $get.l.$broadcastangular-route.min.js:11 (anonymous function)angular.min.js:112 (anonymous function)angular.min.js:126 $get.l.$evalangular.min.js:123 $get.l.$digestangular.min.js:126 $get.l.$applyangular.min.js:81 langular.min.js:86 Oangular.min.js:87 w.onload
angular.min.js.map:1 GET http://192.169.123.1/static/js/vendor/angular.min.js.map 404 (Not Found)
angular-route.min.js.map:1 GET http://192.169.123.1/static/js/vendor/angular-route.min.js.map 404 (Not Found)
```

**Comment by PolygonalTree** [comment]
Check the commit, but I can not see the line where the unexpected  "=" is.

**Comment by qgeissmann** [comment]
in `moreController,js`:

````javascript
$scope.browse=function(folder="/null"){
...
}
```

**Comment by PolygonalTree** [comment]
f66d597 solves that. default variables are only supported on firefox.
